version: '3.8'

services:
  postgres:
    image: postgres
    container_name: audit-listener-postgres
    environment:
      POSTGRES_USER: audit_listener
      POSTGRES_DB: events
      POSTGRES_PASSWORD: 12345
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U audit_listener -d events"]
      interval: 10s
      timeout: 5s
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:9.1.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
      image: kibana:9.1.2
      depends_on:
        - elasticsearch
      ports:
        - "5601:5601"
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

volumes:
  postgres_data:
  elasticsearch_data:
